name: Build pipa images
on:
  push: # Build when push
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 5' # Start build every friday

jobs:
  build-image:
    strategy:
      matrix:
        version: ["default"]

    runs-on: ubuntu-latest
    steps:
      - name: Check out build configurations
        uses: actions/checkout@v4
        
      - name: Create artifact directory
        run: |
            mkdir out
        
      - name: Substitute placeholders in configs
        run: |
           find . -type f -name "*.cfg" -exec sed -i "s|HOME|$(echo $HOME)|;s|NPROC|$(nproc)|" {} +


      - name: Install pmbootstrap from git
        run: |
          git clone --depth=1 https://gitlab.postmarketos.org/postmarketOS/pmbootstrap.git
          mkdir -p ~/.local/bin
          ln -s "$PWD/pmbootstrap/pmbootstrap.py" ~/.local/bin/pmbootstrap
          pmbootstrap --version

       - name: Set up pmaports
         run: |
           echo -e '\n\n' | pmbootstrap init || true
           cd ~/.local/var/pmbootstrap/cache_git/pmaports
           git remote add pmaports-pipa https://github.com/pipa-project/pmaports
           DEFAULT_BRANCH=$(git remote show pmaports-pipa | awk '/HEAD branch/ {print $NF}')
           git fetch pmaports $DEFAULT_BRANCH
           git reset --hard pmaports-pipa/$DEFAULT_BRANCH

       - name: Build the xiaomi-pipa without DE
         run: |
            pmbootstrap install --password 147147
            pmbootstrap export
            cp /tmp/postmarketOS-export/boot.img out/boot-xiaomi-pipa.img
            cp /tmp/postmarketOS-export/xiaomi-pipa.img out/rootfs-xiaomi-pipa-none.img
            
        
        - name: Upload artifacts xiaomi-pipa without DE
          uses: actions/upload-artifact@v4
          with:
            name: xiaomi-pipa-none
            path: out/*.img*
            retention-days: 7

        - name: Build the xiaomi-pipa with KDE Plasma Desktop
          run: |
             rm -r out/*
             pmbootstrap install --password 147147 --add postmarketos-ui-plasma-desktop
             pmbootstrap export
             cp /tmp/postmarketOS-export/boot.img out/boot-xiaomi-pipa.img
             cp /tmp/postmarketOS-export/xiaomi-pipa.img out/rootfs-xiaomi-pipa-plasma.img
            
        
        - name: Upload artifacts xiaomi-pipa with KDE Plasma Desktop
          uses: actions/upload-artifact@v4
          with:
            name: xiaomi-pipa-plasma
            path: out/*.img*
            retention-days: 7
            
        - name: Build the xiaomi-pipa with GNOME
          run: |
             rm -r out/*
             pmbootstrap install --password 147147 --add postmarketos-ui-gnome
             pmbootstrap export
             cp /tmp/postmarketOS-export/boot.img out/boot-xiaomi-pipa.img
             cp /tmp/postmarketOS-export/xiaomi-pipa.img out/rootfs-xiaomi-pipa-gnome.img
            
        
        - name: Upload artifacts xiaomi-pipa with GNOME
          uses: actions/upload-artifact@v4
          with:
            name: xiaomi-pipa-gnome
            path: out/*.img*
            retention-days: 7
            



        

        
